import { t, type DeclarationContent } from 'intlayer';

const certificateVerifyContent = {
  key: 'certificate-verify-page',
  content: {
    verifying: t({
      'zh-CN': '正在验证证书...',
      en: 'Verifying certificate...',
    }),
    verifyFailed: t({
      'zh-CN': '验证失败',
      en: 'Verification Failed',
    }),
    verifyFailedDesc: t({
      'zh-CN': '无法验证该证书，请检查证书ID是否正确',
      en: 'Unable to verify certificate, please check the certificate ID',
    }),
    backBtn: t({
      'zh-CN': '返回浏览器',
      en: 'Back to Explorer',
    }),
    back: t({
      'zh-CN': '返回',
      en: 'Back',
    }),
    valid: t({
      'zh-CN': '证书有效',
      en: 'Certificate Valid',
    }),
    invalid: t({
      'zh-CN': '证书无效',
      en: 'Certificate Invalid',
    }),
    download: t({
      'zh-CN': '下载证书',
      en: 'Download Certificate',
    }),
    downloading: t({
      'zh-CN': '下载中...',
      en: 'Downloading...',
    }),
    certInfo: {
      title: t({
        'zh-CN': '证书信息',
        en: 'Certificate Information',
      }),
      subtitle: t({
        'zh-CN': '区块链存证证书详细信息',
        en: 'Blockchain certification certificate details',
      }),
      certificateId: t({
        'zh-CN': '证书编号',
        en: 'Certificate ID',
      }),
      status: t({
        'zh-CN': '验证状态',
        en: 'Verification Status',
      }),
      verificationTime: t({
        'zh-CN': '验证时间',
        en: 'Verification Time',
      }),
      blockIndex: t({
        'zh-CN': '区块编号',
        en: 'Block Number',
      }),
      certTime: t({
        'zh-CN': '存证时间',
        en: 'Certification Time',
      }),
      knowledge: t({
        'zh-CN': '知识标题',
        en: 'Knowledge Title',
      }),
      author: t({
        'zh-CN': '作者',
        en: 'Author',
      }),
      contentHash: t({
        'zh-CN': '内容哈希',
        en: 'Content Hash',
      }),
    },
    legal: {
      title: t({
        'zh-CN': '法律声明',
        en: 'Legal Statement',
      }),
      statement1: t({
        'zh-CN': '此证书证明该内容已存证于EduChain区块链',
        en: 'This certificate proves that the content has been certified on EduChain blockchain',
      }),
      statement2: t({
        'zh-CN': '本证书由EduChain基于区块链存证的教育知识共享与智能检索系统自动生成，证明相关内容的哈希值和时间戳已被永久记录在区块链上，具有不可篡改性。',
        en: 'This certificate is automatically generated by EduChain blockchain-based educational knowledge sharing and intelligent retrieval system, proving that the hash value and timestamp of the content have been permanently recorded on the blockchain with immutability.',
      }),
      statement3: t({
        'zh-CN': '本证书可作为内容所有权和创建时间的证明，但不代表对内容本身的质量、准确性或合法性的认可。内容的版权归原作者所有。',
        en: 'This certificate can be used as proof of content ownership and creation time, but does not represent endorsement of the quality, accuracy or legality of the content itself. Copyright of the content belongs to the original author.',
      }),
      footer: t({
        'zh-CN': 'EduChain平台 - 教育内容区块链存证系统',
        en: 'EduChain Platform - Educational Content Blockchain Certification System',
      }),
    },
  },
} satisfies DeclarationContent;

export default certificateVerifyContent;
